apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  ports:
    - port: 80
      nodePort: 30080
      protocol: TCP
    - port: 443
      nodePort: 30443
      protocol: TCP
