apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonAnnotations:
  app.kubernetes.io/managed-by: manifests/argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.12/manifests/install.yaml
  - manifests
