apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otel

commonAnnotations:
  app.kubernetes.io/managed-by: manifests/otel

resources:
  - github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.5.0
  - namespace.yaml
