apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-gateway

commonAnnotations:
  app.kubernetes.io/managed-by: manifests/nginx-gateway

resources:
  - github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.5.0
  - namespace.yaml
  - gatewayclass.yaml
  - nginx-gateway.yaml
  - nodeport.yaml

configMapGenerator:
  - name: njs-modules
    files:
      - internal/nginx/modules/src/httpmatches.js
