apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  type: NodePort
  selector:
    app: nginx-gateway
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
      name: https
